name: build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  style:
    name: "Build (Zig version: ${{ matrix.zig-version }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zig-version: [
          "beta", # Latest tagged release.
          # "edge"  # Latest build from Git master branch
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Zig
        run: sudo snap install zig --classic --${{ matrix.zig-version }}

      - name: Build
        run: zig build

      - name: Run End-to-End test
        run: zig build e2e
